# Generated by Django 5.0.7 on 2024-08-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_blogmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
