# Generated by Django 5.0.7 on 2024-08-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
